### ISSUE TITLE
Bug: Load More link showing even if articles are below threshold to load more.

### ISSUE THREAD

**Issue by thinkverse** [dailydotdev/daily-webapp#174]
Hello again.&nbsp; 👋

Found a bug where the `Load More` link is showing, even though the article count is below the threshold to load more.
Seems the `ActivitySection.tsx` isn't taking the article `count` into account when deciding to `const showLoadMore`.

The expected result is that the `Load more ▸` link doesn't show when the article count is below 4 since that's the given threshold. I've come to this threshold number because looking at other profiles the minimum of shown articles at initial profile load is no more than 3.

So the expected result would be that the link shouldn't be shown if the count is 3 or below. Meaning 4 would be the threshold to even consider loading more articles.

## Suggestion of potential fix.

Make `const showLoadMore` take `count` into consideration when calculating showing the link, it's already passed into the component so it's there. Making a check against the threshold to only show the link if the count of articles is below or equal to our threshold. Because if our count is 3, 2, or 1 we cannot load more articles anyway. Only if it's 4 or above can we load in and show more articles.

```javascript
const threshold = 4;

const showLoadMore =
  !showEmptyScreen &&
  !query.isLoading &&
  query.isFetchingMore &&
  query.canFetchMore &&
  count >= threshold;
```

### Screenshot of the expected result.

![Screen shot or load more link not showing when article count it 3 or below](https://user-images.githubusercontent.com/2221746/99818415-7c6e9f00-2b4e-11eb-87ea-0da542c2e244.png)

### Screenshot of the actual result.

![Screen shot of load more link showing even though there is only three articles and cannot load more](https://user-images.githubusercontent.com/2221746/99818181-2dc10500-2b4e-11eb-9185-0d31ab13d25c.png)

**Comment by idoshamun** [comment]
Hey @thinkverse,

Actually, you're right the load more button is not taking into account the article count.
In our pagination response, we return a flag whether there's another page or not.
When the response count equals the page size it creates this bug. 
It's something that I need to solve on our backend.
I'll let you know once I solve it, thanks for reporting :)

**Comment by thinkverse** [comment]
Awesome! Hopefully, the issue isn't a hard one to fix.
Would hate to have you scratching your head over a rather trivial UI bug. 🙂

**Comment by idoshamun** [comment]
Fixed! It will be automatically deployed to production in a few minutes 🚀
