### ISSUE TITLE
New feature - top sites

### ISSUE THREAD

**Issue by Krausso** [dailydotdev/daily-webapp#362]
![image](https://user-images.githubusercontent.com/52201020/108603523-0ed24900-73b1-11eb-9956-cc4cd9a81f4f.png)

Recently, I installed a daily.dev extension, but I have few pinned websites that I visit so many times per hour.
I think that'd be a great idea if you made a feature that gives someone an opportunity to pin certain websites

**Comment by idoshamun** [comment]
Hey @Krausso,

Thanks for submitting your idea and dedicating the time to creating the mockup :)
Currently, we support the built-in browser's API for receiving the last visited websites and you can enable it by approving the needed permissions.
We don't have a plan for the near future to allow customizations of this list as we rely on the browser's API.
I hope you understand.

P.S. For next time it's better to open the issue in our main repo https://github.com/dailydotdev/daily

Thanks again 🙏
