### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by solancer** [dailydotdev/daily-webapp#9]
npm install and dev is a dead end, some sort of backend code is needed. Any info on this would be helpful

![Screenshot 2020-08-25 at 10 46 51 pm](https://user-images.githubusercontent.com/800668/91206570-001e1880-e725-11ea-88b4-fcaf9ecc3cdb.png)

**Comment by idoshamun** [comment]
Hey!
In order to run the code, you need to set up a local environment of daily.dev.
Check out the instructions here:
https://github.com/dailydotdev/daily#-running-dailydev-locally
